DROP TABLE IF EXISTS STG_TMPL_ACCT;
DROP TABLE IF EXISTS STG_TMPL_MSTR;
DROP TABLE IF EXISTS STG_PLN_BRNCH;
DROP TABLE IF EXISTS STG_PLN_MSTR;
DROP TABLE IF EXISTS STG_PRD_MSTR;

CREATE TABLE STG_PRD_MSTR
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    PRD_NM VARCHAR(100) NOT NULL ,
    PRD_CD VARCHAR(50) NOT NULL UNIQUE ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);


CREATE TABLE STG_PLN_MSTR
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    PLN_NM VARCHAR(100) NOT NULL ,
    PLN_CD VARCHAR(50) NOT NULL ,
    BILL_CD VARCHAR(50) NOT NULL ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);



CREATE TABLE STG_PLN_BRNCH
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    PLN_ID INT NOT NULL REFERENCES STG_PLN_MSTR(ID),
    BRNCH_ID VARCHAR(50) NOT NULL ,
    BILL_CD VARCHAR(50) NOT NULL ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);


CREATE TABLE STG_TMPL_MSTR
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    TMPL_NM VARCHAR(100) NOT NULL ,
    PRD_CD VARCHAR(50) REFERENCES STG_PRD_MSTR (PRD_CD),
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);



CREATE TABLE STG_TMPL_ACCT
(
    ID INT REFERENCES STG_TMPL_MSTR(ID),
    ACCT_NUM VARCHAR(50) NOT NULL ,
    PLN_ID INT NOT NULL REFERENCES STG_PLN_MSTR(ID),
    BRNCH_ID INT NOT NULL ,
    JOB_ID VARCHAR(50) ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);



INSERT INTO STG_PRD_MSTR (PRD_NM, PRD_CD) VALUES ('Advices', 'ADV01');
INSERT INTO STG_PRD_MSTR (PRD_NM, PRD_CD) VALUES ('Statements', 'STM01');

INSERT INTO STG_PLN_MSTR (PLN_NM, PLN_CD, BILL_CD) VALUES ('Basic Plan', 'B000', 2145);
INSERT INTO STG_PLN_MSTR (PLN_NM, PLN_CD, BILL_CD) VALUES ('Standard Plan', 'S000', 7145);
INSERT INTO STG_PLN_MSTR (PLN_NM, PLN_CD, BILL_CD) VALUES ('Premium Plan', 'PR00', 8129);
INSERT INTO STG_PLN_MSTR (PLN_NM, PLN_CD, BILL_CD) VALUES ('Platinum Plan', 'PL00', 3773);

INSERT INTO STG_PLN_BRNCH (PLN_ID, BRNCH_ID, BILL_CD) VALUES (1, 640, 2145);
INSERT INTO STG_PLN_BRNCH (PLN_ID, BRNCH_ID, BILL_CD) VALUES (1, 270, 4214);
INSERT INTO STG_PLN_BRNCH (PLN_ID, BRNCH_ID, BILL_CD) VALUES (1, 500, 7832);
INSERT INTO STG_PLN_BRNCH (PLN_ID, BRNCH_ID, BILL_CD) VALUES (3, 577, 8129);

INSERT INTO STG_TMPL_MSTR (TMPL_NM, PRD_CD) VALUES ('Debit Advice for London Branch', 'ADV01');
INSERT INTO STG_TMPL_MSTR (TMPL_NM, PRD_CD) VALUES ('Debit Advice for China', 'ADV01');
INSERT INTO STG_TMPL_MSTR (TMPL_NM, PRD_CD) VALUES ('Credit Advice for Brazil', 'ADV01');

INSERT INTO STG_TMPL_ACCT (ID, ACCT_NUM, PLN_ID, BRNCH_ID, JOB_ID) VALUES (1,'99837429',1,640,'adfc-decr-uzpd');
INSERT INTO STG_TMPL_ACCT (ID, ACCT_NUM, PLN_ID, BRNCH_ID, JOB_ID) VALUES (2,'77247433',1,270,null);
INSERT INTO STG_TMPL_ACCT (ID, ACCT_NUM, PLN_ID, BRNCH_ID, JOB_ID) VALUES (3,'80842876',1,500,'ppef-cdg-xert');
INSERT INTO STG_TMPL_ACCT (ID, ACCT_NUM, PLN_ID, BRNCH_ID, JOB_ID) VALUES (1,'99837429',1,640, null);
