@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class STG_PLN_BRNCH {
   PLN_ID: int(11)
   BRNCH_ID: varchar(50)
   BILL_CD: varchar(50)
   CRT_DT: datetime
   UPD_DT: datetime
   ACTIVE: char(1)
   CRT_USR: varchar(100)
   UPD_USR: varchar(100)
   ID: int(11)
}
class STG_PLN_MSTR {
   PLN_NM: varchar(100)
   PLN_CD: varchar(50)
   BILL_CD: varchar(50)
   CRT_DT: datetime
   UPD_DT: datetime
   ACTIVE: char(1)
   CRT_USR: varchar(100)
   UPD_USR: varchar(100)
   ID: int(11)
}
class STG_PRD_MSTR {
   PRD_NM: varchar(100)
   PRD_CD: varchar(50)
   CRT_DT: datetime
   UPD_DT: datetime
   ACTIVE: char(1)
   CRT_USR: varchar(100)
   UPD_USR: varchar(100)
   ID: int(11)
}
class STG_TMPL_ACCT {
   ID: int(11)
   ACCT_NUM: varchar(50)
   PLN_ID: int(11)
   BRNCH_ID: int(11)
   JOB_ID: varchar(50)
   CRT_DT: datetime
   UPD_DT: datetime
   ACTIVE: char(1)
   CRT_USR: varchar(100)
   UPD_USR: varchar(100)
}
class STG_TMPL_MSTR {
   TMPL_NM: varchar(100)
   PRD_CD: varchar(50)
   CRT_DT: datetime
   UPD_DT: datetime
   ACTIVE: char(1)
   CRT_USR: varchar(100)
   UPD_USR: varchar(100)
   ID: int(11)
}

STG_PLN_BRNCH  -[#595959,plain]-^  STG_PLN_MSTR  : "PLN_ID:ID"
STG_TMPL_ACCT  -[#595959,plain]-^  STG_PLN_MSTR  : "PLN_ID:ID"
STG_TMPL_ACCT  -[#595959,plain]-^  STG_TMPL_MSTR : "ID"
STG_TMPL_MSTR  -[#595959,plain]-^  STG_PRD_MSTR  : "PRD_CD"
@enduml
