DROP TABLE IF EXISTS STG_TMPL_ACCT;
DROP TABLE IF EXISTS STG_TMPL_MSTR;
DROP TABLE IF EXISTS STG_PLN_BRNCH;
DROP TABLE IF EXISTS STG_PLN_MSTR;
DROP TABLE IF EXISTS STG_PRD_MSTR;

CREATE TABLE STG_PRD_MSTR
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    PRD_NM VARCHAR(100) NOT NULL ,
    PRD_CD VARCHAR(50) NOT NULL UNIQUE ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);


CREATE TABLE STG_PLN_MSTR
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    PLN_NM VARCHAR(100) NOT NULL ,
    PLN_CD VARCHAR(50) NOT NULL ,
    BILL_CD VARCHAR(50) NOT NULL ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);



CREATE TABLE STG_PLN_BRNCH
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    PLN_ID INT NOT NULL REFERENCES STG_PLN_MSTR(ID),
    BRNCH_ID VARCHAR(50) NOT NULL ,
    BILL_CD VARCHAR(50) NOT NULL ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);


CREATE TABLE STG_TMPL_MSTR
(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    TMPL_NM VARCHAR(100) NOT NULL ,
    PRD_CD VARCHAR(50) REFERENCES STG_PRD_MSTR (PRD_CD),
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);



CREATE TABLE STG_TMPL_ACCT
(
    ID INT REFERENCES STG_TMPL_MSTR(ID),
    ACCT_NUM VARCHAR(50) NOT NULL ,
    PLN_ID INT NOT NULL REFERENCES STG_PLN_MSTR(ID),
    BRNCH_ID INT NOT NULL ,
    JOB_ID VARCHAR(10) ,
    CRT_DT DATETIME DEFAULT NOW(),
    UPD_DT DATETIME DEFAULT NOW(),
    ACTIVE CHAR(1) DEFAULT 'Y',
    CRT_USR VARCHAR(100) DEFAULT 'SYS',
    UPD_USR VARCHAR(100) DEFAULT 'SYS'
);

