spring:
  data:
    mongodb:
      database: Productsdb
      host: localhost
      port: 27017
  application:
    name: webflux-mongo


server:
  port: 8081

person:
  ms:
    url: http://localhost:8080/playground/person/stream/{uid}